### ISSUE TITLE
feat: Trigger warnings based on package.json version numbers

### ISSUE THREAD

**Issue by brandonpittman** [evinism/timebomb#3]
Intrigued by this project! Was thinking about how it would be nice to trigger off a certain version number as well. Would you be open to PRs adding that kind of feature?

Thanks!

**Comment by evinism** [comment]
I'm very open to PRs! What interface are you proposing?

**Comment by brandonpittman** [comment]
@evinism To not break the existing API, maybe add matching named exports like

```ts
import { warnAfterVersion, failAfterVersion, slowAfterVersion } from "timebomb-js";

const foo = () => {
  warnAfterVersion("2.0")
   // ...
}
```

The trick would be getting the version number. It would be best if it was pulling from your `package.json`. This might required something like dotenv for browser code though.

**Comment by evinism** [comment]
Fantastic, thanks!
